language: node_js

node_js:
  - "5"

branches:
  only:
    - master

before_script:
  - npm install -g karma-cli
  - npm install -g gulp-cli
  - npm install

script:
  - npm start
  - npm test

addons:
    code_climate:
        repo_token: ecf33ca3ef2bbd6a1a642750e803cc2fb75dd176b54d3032a9336a5c9cebe372