language: node_js

node_js:
  - "5"

branches:
  only:
    - master

before_script:
  - npm install -g karma-cli
  - npm install -g gulp-cli
  - npm install

script:
  - npm start
  - npm test

after_script:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js